name: ae598-arp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - git
  - jupyter
  - ipympl
  - numpy
  - scipy
  - sympy
  - matplotlib
  - pinocchio
  - meshcat-python
  - meshcat-shapes
  - pytorch
  - torchvision
  - tensorboard
  - qpsolvers
  - mediapy
  - robot_descriptions
  - pip:
    - mujoco>=3.4.0
    - 'stable-baselines3[extra]'
    - 'gymnasium[mujoco]'
